######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 10 12:59:56 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . .
INCLUDEPATH += .

# Input
HEADERS += launcher.h
SOURCES += aboutwindow.cpp io.cpp main.cpp mainwindow.cpp
